In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
type(a)

numpy.ndarray

In [5]:
#creating a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [9]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)

(2, 5)
2
int64


In [12]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.random.randint(1,11, size=(2,3))

array([[2, 5, 8],
       [3, 5, 2]], dtype=int32)

In [14]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]
